articles/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.ArticleView.as_view()),
    path("<slug:slug>/", views.ArticleDetailView.as_view(), name="article_detail")
]

mainapp/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("about/", views.about, name='about'),
    path("mentalarithm/", views.mentalarithm, name='mentalarithm'),
    path("speedreading/", views.speedreading, name='speedreading'),
    path("reading/", views.reading, name='reading'),
    path("calligraphy/", views.calligraphy, name='calligraphy'),
    path("triallesson/", views.triallesson, name='triallesson'),
    path("main/", views.LessonView.as_view()),
    path("<slug:slug>/", views.LessonDetailView.as_view(), name="lesson_detail"),
    path("trial/<int:pk>/", views.AddTrial.as_view(), name='add_trial'),
]

mental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("reviews/", include('reviews.urls')),
    path("articles/", include('articles.urls')),
    path("", include('mainapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.MoviesView.as_view()),
    path("<slug:slug>/", views.MovieDetailView.as_view(), name="review_detail"),
    path("review/<int:pk>/", views.AddReview.as_view(), name='add_review'),
]

articles/models.py
from django.db import models
from datetime import date
from django.urls import reverse



class Article(models.Model):
    title = models.CharField("Название", max_length=120)
    post = models.TextField("Содержание статьи")
    date = models.DateTimeField("Дата публикации")
    poster = models.ImageField("Постер", upload_to="articles/")
    url = models.SlugField(max_length=130, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("article_detail", kwargs={"slug": self.url})

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

mainapp/models.py
from django.db import models
from django.urls import reverse


class Lesson(models.Model):
    title = models.TextField("Занятие", max_length=1000, blank=True)
    url = models.SlugField(max_length=130, unique=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("lesson_detail", kwargs={"slug": self.url})

    class Meta:
        verbose_name = "Пробное занятие"
        verbose_name_plural = "Пробное занятие"


class Trial(models.Model):
    name = models.CharField("Имя", max_length=100)
    email = models.EmailField()
    phone = models.TextField("Номер телефона", max_length=12)
    
    lesson = models.ForeignKey(
        Lesson, verbose_name="главное сообщение", blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.lesson}"

    class Meta:
        verbose_name = "Форма заполнения"
        verbose_name_plural = "Форма заполнения"

    

reviews/models.py
from django.db import models
from datetime import date
from django.urls import reverse


class Movie(models.Model):
    title = models.TextField("Главное", max_length=2000)
    poster = models.ImageField("Постер", upload_to="reviews/")
    url = models.SlugField(max_length=130, unique=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("review_detail", kwargs={"slug": self.url})

    class Meta:
        verbose_name = "Главное"
        verbose_name_plural = "Главное"



class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    movie = models.ForeignKey(
        Movie, verbose_name="главное сообщение", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

mainapp/forms.py
from django import forms
from .models import Trial


class TrialForm(forms.ModelForm):
    class Meta:
        model = Trial
        fields = ("name", "email", "phone")

reviews/forms.py
from django import forms

from .models import Reviews


class ReviewForm(forms.ModelForm):
    """Форма отзывов"""
    class Meta:
        model = Reviews
        fields = ("name", "email", "text")

articles/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.base import View
from .models import Article



class ArticleView(ListView):
    """Список статей"""
    model = Article
    queryset = Article.objects.all()
    template_name = "articles/articles_list"



class ArticleDetailView(DetailView):
    """Полное описание статьи"""
    model = Article
    slug_field = "url"

mainapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View
from .models import Lesson, Trial
from .forms import TrialForm


    
def about(request):
    return render(request, 'articles/about.html')

def mentalarithm(request):
    return render(request, 'articles/mentalarithm.html')

def speedreading(request):
    return render(request, 'articles/speedreading.html')

def reading(request):
    return render(request, 'articles/reading.html')

def calligraphy(request):
    return render(request, 'articles/calligraphy.html')

def triallesson(request):
    return render(request, 'articles/triallesson.html')



class LessonView(View):
    def get(self, request):
        lessons = Lesson.objects.all()
        return render(request, "articles/mainpage.html", {"lesson_list": lessons})



class LessonDetailView(View):
    def get(self, request, slug):
        lesson = Lesson.objects.get(url=slug)
        return render(request, "articles/lesson_detail.html", {"lesson": lesson})



class AddTrial(View):
    def post(self, request, pk):
        form = TrialForm(request.POST)
        lesson = Lesson.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.lesson = lesson
            form.save()
        return redirect("/main")

reviews/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View
from .models import Movie, Reviews
from .forms import ReviewForm



class MoviesView(View):
    def get(self, request):
        movies = Movie.objects.all()
        return render(request, "articles/review_list.html", {"movie_list": movies})




class MovieDetailView(View):
    def get(self, request, slug):
        movie = Movie.objects.get(url=slug)
        return render(request, "articles/review_detail.html", {"movie": movie})
    

class AddReview(View):
    """Отзывы"""
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.movie = movie
            form.save()
        return redirect("/reviews/main")

templates/articles/about.html
{% extends 'articles/base.html' %}
{% load static %}
{% block movie %}  
<div class="mental" style="color: black; margin-left: 100px; margin-right: 100px;  "> 
      <div class="mental" style="text-align: center; font-weight:bold; font-size:20px;">О нас</div><br>
<div style="text-indent: 25px;">Центр Развития "Азбука Интеллекта" — это центр с особой атмосферой, отношением к детям и любовью к математике и науке.</div>
    <div style="text-indent: 25px;">Нашему Центру 3 года и ежегодно мы обучаем более 150 детей.</div>
    <div style="text-indent: 25px;">Своей главной задачей мы видим развитие детей в математике через атмосферу радости, комфорта и ситуаций успеха. Мы искренне верим, 
      что если ребенок не любит математику, то это не навсегда, — любую ситуацию можно исправить через правильных людей. Именно такие работают в нашем центре.</div>
    <div style="text-indent: 25px;">У нас есть образовательная лицензия, что говорит о нашей надёжности. Каждая наша программа продумана и спроектирована так, чтобы у 
      вашего ребенка получились самые наилучшие для него результаты.</div>
    <div style="text-indent: 25px;">Каждый год мы принимаем участие в разных олимпиадах по математике и ментальной арифметике.  Мы уверены, что если и выбирать Центр 
      для своего ребенка, то "Азбука Интеллекта" — это то, что нужно!</div>
    <div style="text-indent: 25px;"></div>
</div>

{% endblock movie %}

templates/articles/article_detail.html
{% extends 'articles/base.html' %}
{% block movie %}
    
        <div class="container py-md-3">
        
            <div class="row">
                
                <div class="left-ads-display col-lg-8">
                    
                    <div class="row sub-para-w3layouts mt-5">

                        <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                            {{ article.title }}</h3>
                        <p>
                            <img src="{{ article.poster.url }}" class="img-fluid" alt="">
                            
                        </p>
                        <p class="editContent" style="outline: none; cursor: inherit; color:black">{{ article.post }}</p>
                        
                        <p class="editContent" style="outline: none; cursor: inherit; color:black">{{ article.date }}</p>
                       
                    
                    </div>
                    
                    
                </div>
            </div>
        </div>
        {% endblock movie %}    
    

templates/articles/article_list.html
{% extends 'articles/base.html' %}

{% block movie %} 
            <div class="left-ads-display col-lg-9">
              <div class="row" style="margin-left: 250px">
                {% for article in article_list %}
                <div class="col-md-4 product-men">
                  <div
                    class="product-shoe-info editContent text-center mt-lg-4"
                  >
                  <div class="men-thumb-item">
                    <img src="{{ article.poster.url }}" class="img-fluid" alt="" >
                </div>
                    <div class="item-info-product">
                      <h4 class="">
                        <a
                          href="{{ article.get_absolute_url }}"
                          class="editContent"
                          >{{ article.title }}</a
                        >
                      </h4>
                      
                    </div>
                  </div>
                </div>
                {% endfor%}
              </div>
            
              <!--<div class="grid-img-right mt-4 text-right bg bg1" >
                            <span class="money editContent" >Flat 50% Off</span>
                            <a href="moviesingle.html" class="btn" >Now</a>
                        </div>-->
            </div>
{% endblock movie %}
  
          
          

templates/articles/base.html
{% extends 'base.html' %}
<!-- {% block title %} {% endblock title %} -->
{% block content %}
<section
  class="ab-info-main py-md-5 py-4 editContent"
  style="padding-left: 3rem; padding-right: 3rem;">
  <div class="container-fluid py-md-3">
    <div class="row">
      
      {% block movie %} {% endblock movie %}
    </div>
  </div>
</section>
{% endblock content %}

templates/articles/calligraphy.html
{% extends 'articles/base.html' %} {% block movie %}
<div class="mental" style="color: black; margin-left: 100px; margin-right: 100px;  "> 
    <div class="mental" style="text-align: center; font-weight:bold; font-size:20px;">Что такое Каллиграфия?</div><br>
    <div style="text-indent: 25px;">Дословный перевод слова «каллиграфия» – красивое письмо. Отсюда и наиболее расхожее определение – искусство красиво писать. 
        И пожалуй, главное слово здесь – искусство. Каллиграфия всегда была связана с некой элитарностью, даже когда служила вполне конкретным целям.</div>
    <div style="text-indent: 25px;">На Востоке, например, в Китае, каллиграфия считается традиционным видом искусства наравне с поэзией и живописью, а также служит 
        формой медитации. В странах ислама каллиграфическое искусство и является практически единственным выразительным средством.</div>
    <div style="text-indent: 25px;">История каллиграфии неразрывно связана с историей письменности и эволюцией шрифтов. Письмо, как мы знаем, ведёт начало от простейших 
        знаковых рисунков, проходя этап клинописи и иероглифов, чтобы, наконец, стать условным графическим изображением устной речи: собственно алфавитом.

        Латинская, а впоследствии и общеевропейская письменность сформировалась на основе греческого и этрусского алфавитов. Интересно, что ещё до греков существовало 
        два вида написания букв. Затейливый, почти орнаментальный вариант обычно украшал памятники и монументы, а в книгах и рукописях использовался более простой и 
        понятный стиль.</div>
    <div style="text-indent: 25px;">Упрощению греческого алфавита способствовали римляне, а вот развитию шрифтов христианство. Необходимость переписывания Библии открыла
         новые возможности. С V века наиболее распространённым становится маюскульный или унциальный шрифт, особенность которого состоит в том, что заглавные буквы не 
         соединяются между собой. Распространившись по всей Европе, этот шрифт, естественно, обзавелся многочисленными региональными вариациями и местными почерками.

        Переворот происходит в VII веке и связан с правлением Карла Великого, который дал указ о создании единого шрифта. Были разработаны грамматические правила, 
        закреплены определённые функции за большими и малыми буквами. Кроме того буквы стали писаться слитно. Этот шрифт получил название каролингского минускула, и 
        основными его положениями мы пользуемся до сих пор.</div>
    <div style="text-indent: 25px;">Готический стиль, охвативший Европу с XI века, породил и готический шрифт. Ломаные, угловатые формы букв сменили унциальные, и 
        существовали вплоть до эпохи Возрождения. Великого поэта Петрарку можно назвать первым каллиграфом, в современном смысле этого слова: именно он в своём увлечении 
        письмом возродил классические доготические формы и назвал их антиквенными.</div>
    <div style="text-indent: 25px;">Казалось бы, изобретение печатного станка в начале XVI века должно было положить конец рукописным шрифтам. С одной стороны, так и 
        случилось: на их основе были созданы гарнитуры для печатных шрифтов. Но именно потеряв свою утилитарную функцию, письмо стало развиваться лишь ради красоты, 
        экспрессии и оригинальности, что и является основными признаками каллиграфии.

        Каллиграфическим почерком писали письма, подписывали официальные документы, оформляли приглашения. В конце XIX века началась эра «печатной машинки», но в то же 
        время произошло и новое возрождение каллиграфии.</div>
    <div style="text-indent: 25px;">Основой каллиграфии в прошлом было созвучие ясности, изящества и красоты без потери читаемости и удобства. Сейчас можно наблюдать 
        обратную ситуацию: в век технологий, когда чёткость достигается очень простыми методами, а аккуратность граничит со скукой, каллиграфия, возможно, теряет свою 
        изначальную сущность. Это уже не искусство красивого письма, а искусство самовыражения с помощью письма.</div>
    <div style="text-indent: 25px;">Таким образом, сегодня каллиграфия стала самостоятельным видом искусства, своеобразной живописью. В произведениях современных 
        художников-каллиграфов буквы могут сочетаться с экспрессивными абстрактными мазками, различными фактурами, создавая впечатление даже некой недоделанности. 
        Прекрасным примером такого творчества являются работы современной французской художницы Софи Вербеек.</div>
    <div style="text-indent: 25px;">Закончить хотелось бы цитатой известного немецкого каллиграфа Германа Цапфа: «Каллиграфия – это мирное и благородное искусство, 
        удел хорошо образованных людей, работающих с полной отдачей и усердием: в штрихи и буквы мы вкладываем наши чувства и переживания, частицу самих себя».</div>
    
{% endblock movie %}

templates/articles/lesson_detail.html
{% extends 'articles/base.html' %}
{% block movie %}
<div class="left-ads-display col-lg-8">
  
<h3 class="editContent" style="outline: none; cursor: inherit; margin-left: 180px; margin-bottom: 30px;">
    {{ lesson.title }}
</h3>
<hr width="1000" align="left" size="24">
<div class="row">
<div class="single-form-left">
<div class="contact-single">
  
  <h3 class="editContent" style="outline: none; cursor: inherit; margin-left: 190px; margin-top: 20px;"> 
    <span
      class="sub-tittle editContent"
      style="outline: none; cursor: inherit; " 
    ></span
    >Оставить заявку на пробное занятие
  </h3>
  <form action="{% url 'add_trial' lesson.id %}" method="post" class="mt-4" style="margin-left: 190px;">
    {% csrf_token %}

    <div
      class="col-sm-6 form-group p-0 editContent"
      style="outline: none; cursor: inherit; "
    >
      <label
        for="contactusername"
        class="editContent"
        style="outline: none; cursor: inherit;"
        >ФИО:
      </label>
      <input
        type="text"
        class="form-control border"
        name="name"
        id="contactusername"
        required=""
      />
    </div>
    <div
      class="col-sm-6 form-group p-0 editContent"
      style="outline: none; cursor: inherit;"
    >
      <label
        for="contactemail"
        class="editContent"
        style="outline: none; cursor: inherit;"
        >Email:
      </label>
      <input
        type="email"
        class="form-control border"
        name="email"
        id="contactemail"
        required=""
      />
    </div>
    <div
      class="col-sm-6 form-group p-0 editContent"
      style="outline: none; cursor: inherit;"
    >
      <label
        for="contactusername"
        class="editContent"
        style="outline: none; cursor: inherit;"
        >Номер телефона:
      </label>
      <input
        type="text"
        class="form-control border"
        name="phone"
        id="contactusername"
        required=""
      />
    </div>

    <button 
      type="submit"
      class="mt-3 btn btn-success btn-block py-3"
      style="outline: none; cursor: inherit;  width:100 px; " 
    >
      Отправить
    </button>
  </form>
</div>
</div>
</div>
</div>
{% endblock movie %}

templates/articles/reading.html
{% extends 'articles/base.html' %} {% block movie %}
<div class="mental" style="color: black; margin-left: 100px; margin-right: 100px;  "> 
    <div class="mental" style="text-align: center; font-weight:bold; font-size:20px;">Обучение чтению</div><br>
    <div style="text-indent: 25px;">Перед тем, как начать обучение чтению дошкольника, каждый родитель должен задать себе вопрос, зачем им всем это надо.</div><br>
    <div class="mental" style="text-align: center; font-weight:bold; font-size:18px;">Зачем и когда</div>
    <div style="text-indent: 25px;">Если за стремлением  родителей научить ребенка читать  не скрываются гордость и тщеславие («А мой ребенок научился читать в 3 года!»), 
        то есть два условия, при которых  надо начинать обучение. Первое – если ребенок интересуется буквами самостоятельно. Второе – если он не интересуется, но 
        приближается школа, а в школе хоть и должны учить читать, но хотят видеть первоклассников уже умеющими это делать.  В этом варианте дети, которые умеют читать до 
        школы проще пройдут адаптационный период, но начинать обучение следует не раньше 5,5 – 6 лет.</div>
    <div style="text-indent: 25px;">Существует множество различных методик по обучению чтению. Лучший вариант – комбинация этих методик. Например, обучение можно начать с
         букваря Жуковой, играя в кубики (Зайцева, Чаплыгина), запоминая слова на карточках Домана. Не стоит забывать, что перед началом обучения чтению, ребенок должен 
         знать буквы, поскольку последовательность обучения такова: буквы, слога, слова, предложения. Если ребенок может повторить написанное вами слово (сложить его из 
         кубиков, например), значит, к обучению чтению он готов.</div>
         <div class="mental" style="text-align: center; font-weight:bold; font-size:18px;">Как</div>
    <div style="text-indent: 25px;">Многие делают ошибку, когда начинают самостоятельно обучать детей читать. Так, родители пытаются донести мысль, что «МАМА» — это «ЭМ»,
         «А», «ЭМ», «А». Это неправильный подход. Учиться читать надо слогами, соответственно, запоминать надо слоги. Важно знать, что обучение чтению — это развитие памяти.
          Чтобы ребенку запомнить навсегда что-то новое, ему это надо показать и назвать около 600 раз. Ребенок просто запоминает (а не понимает, как принято считать), как
           пишутся буквы, читаются слоги, слова и предложения. Создайте вспомогательную среду дома – окружите ребенка слоговыми таблицами, буквами в кубиках, на магнитах и т.д. 
           Чем чаще он будет видеть буквы, тем быстрее к ним привыкнет и запомнит.</div>
    <div style="text-indent: 25px;">Техника обучения: сначала взрослый читает сам и водит своим пальцем или указкой по тексту, чтобы ребенок видел, что он читает. Так читать 
        ребенку можно от месяца до трех, минут по 10-15 в день. Затем можно читать, показывая пальчиком ребенка, то есть, двигая по тексту его руку. На этот этап можно 
        потратить от недели до месяца. И только после этого, приступаем непосредственно к самому обучению: сначала читаем слог сами, а затем просим повторить ребенка. Когда 
        ребенок научится читать простые слоги, можно приступать к словам, также сначала прочитав ему слово вслух, а затем попросить ребенка повторить.</div><br>
    <div style="text-indent: 25px;">И напоследок 5 правил для успешного обучения чтению:</div><br>
    <div style="text-indent: 25px;">1. Старайтесь заинтересовать ребенка. Это нетрудно сделать, благо существуют различные пособия, тетради, развивающие кубики и игры.</div>
    <div style="text-indent: 25px;">2. Главное не длительность занятий, а их частота. Необходимо, чтобы занятия были регулярными.</div>
    <div style="text-indent: 25px;">3. После зарядки для ума, делайте с ребенком обычную зарядку – подвижные игры хорошо снимут умственное напряжение.</div>
    <div style="text-indent: 25px;">4. Не требуйте невозможного. Если ребенок не хочет заниматься, отложите свои амбиции и проанализируйте, что было сделано не так. Имейте 
        терпение.</div>
    <div style="text-indent: 25px;">5. Не сравнивайте своего ребенка с другими детьми.</div><br>
    <div style="text-indent: 25px;">Когда ребенок обучился чтению, родители облегченно вдохнули, мол, наконец, всё сам теперь читать будет. Но не тут-то было: психологи 
        рекомендуют читать детям книги вслух до 14 лет для их полноценного эмоционального развития.</div>
    

</div>
{% endblock movie %}

templates/articles/review_detail.html
{% extends 'articles/base.html' %}
{% block movie %}
                <div class="left-ads-display col-lg-8" style="margin-left: 250px;">
                    <div class="row">
                        
                        <div class=" col-md-6 pl-lg-4" style="margin-left: 350px; margin-bottom: 30px;">
                            <h3 class="editContent" style="outline: none; cursor: inherit;">
                                {{ movie.title }}
                            </h3>
                              
                        </div>
                    </div>
                   
                    <hr>
                    <div class="row" style="margin-left: 250px; margin-top: 50px;">
                        <div class="single-form-left" >
                            <!-- contact form grid -->
                            <div class="contact-single" >
                                <h3 class="editContent" style="outline: none; cursor: inherit;">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;"></span>Оставить отзыв</h3>
                                <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4">
                                    {% csrf_token %}
                                    <div class="form-group editContent"
                                         style="outline: none; cursor: inherit;">
                                        <label for="contactcomment" class="editContent"
                                               style="outline: none; cursor: inherit;">Ваш комментарий: 
                                            </label>
                                        <textarea class="form-control border" rows="5" name="text"
                                                  id="contactcomment" required=""></textarea>
                                    </div>
                                    <div class="d-sm-flex">
                                        <div class="col-sm-6 form-group p-0 editContent"
                                             style="outline: none; cursor: inherit;">
                                            <label for="contactusername" class="editContent"
                                                   style="outline: none; cursor: inherit;">ФИО:
                                                </label>
                                            <input type="text" class="form-control border" name="name"
                                                   id="contactusername" required="">
                                        </div>
                                        <div class="col-sm-6 form-group ml-sm-3 editContent" 
                                             style="outline: none; cursor: inherit;">
                                            <label for="contactemail" class="editContent"
                                                   style="outline: none; cursor: inherit;">Email:
                                                </label>
                                            <input type="email" class="form-control border" name="email"
                                                   id="contactemail" required="">
                                        </div>
                                    </div>
                                    <button type="submit"
                                            class="mt-3 btn btn-success btn-block py-3"
                                            style="outline: none; cursor: inherit;">Отправить
                                    </button>
                                </form>
                            </div>
                            
                        </div>
                        </div>
                        {% for review in movie.reviews_set.all %}
                        <div class="media py-5" style="margin-left: 70px;">
                            
                            <div class="media-body mt-4">
                                <h5 class="mt-0 editContent"
                                    style="outline: none; cursor: inherit;">{{ review.name }}</h5>
                                <p class="mt-2 editContent" style="outline: none; cursor: inherit;">
                                    {{ review.text }}
                                </p>
                                
                            </div>
                        </div>
                    
                    {% endfor %}
                </div>
                {% endblock movie %}         

templates/articles/review_list.html
{% extends 'articles/base.html' %}

{% block movie %}            
                <div class="left-ads-display col-lg-9">
                    <div class="row">
                      {% for movie in movie_list %}
                      <div class="col-md-4 product-men">
                        <div
                          class="product-shoe-info editContent text-center mt-lg-4"
                        >
                          <div class="men-thumb-item">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                          </div>
                          <div class="item-info-product">
                            <h4 class="">
                              <a href="{{ movie.get_absolute_url }}" class="editContent"
                                >{{ movie.title }}</a
                              >
                            </h4>
      
                            <div class="product_price">
                              <div class="grid-price">
                                <span class="money editContent"
                                  ></span
                                >
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      {% endfor%}
                    </div>
                    <!--<div class="grid-img-right mt-4 text-right bg bg1" >
                                  <span class="money editContent" >Flat 50% Off</span>
                                  <a href="moviesingle.html" class="btn" >Now</a>
                              </div>-->
                  </div>
    {% endblock movie %}
    

templates/articles/triallesson.html
{% extends 'articles/base.html' %}
{% block movie %}  
<div class="mental" style="text-align: center; font-weight:bold; font-size:20px;">Запись на бесплатное пробное занятие</div><br>

<div style="text-indent: 25px; margin-right: 1000px; margin-top: 20px">Номер телефона: +7 (925) 375-33-73</div><br>
<div style="text-indent: 25px;">Почтовый ящик: takaeva.zulfira@mail.ru </div><br>
{% endblock movie %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <!-- //Meta tag Keywords -->
    <title>Азбука Интеллекта</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- //Meta tag Keywords -->
    <!-- Custom-Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <!-- Bootstrap-Core-CSS -->
    <!--/ Style-CSS -->
    <link
      rel="stylesheet"
      href="{% static 'css/style.css' %}"
      type="text/css"
      media="all"
    />
    <!--// Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" />
    <!-- //font-awesome-icons -->
    <!-- /Fonts -->
    <link
      href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700"
      rel="stylesheet"
    />
    <link
      href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900"
      rel="stylesheet"
    />
    <!-- //Fonts -->
  </head>
  <body>
    <div id="page" class="page">
      <div
        class="main-banner bg {% block header %} {% endblock header %}" id="home">
        {% include 'include/header.html' %}
      </div>
      <ol class="breadcrumb editContent">
        <li class="breadcrumb-item">
          <a href="/main" class="editContent">Home</a>
        </li>
        <li class="breadcrumb-item active editContent">Single Page</li>
      </ol>
      {% block content %} {% endblock content %} 
      {% include 'include/footer.html' %}
    </div>
  </body>
</html>